name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20.x'

    - name: Build
      run: |
        make cloudflared

    - name: upload_cloudflared
      uses: actions/upload-artifact@v3
      with:
        name: cloudflared
        path: cloudflared